### ISSUE TITLE
Can I use it from powershell?

### ISSUE THREAD

**Issue by rerime** [GrzegorzBlok/FastRsyncNet#1]
Goal is copy only delta file from powershell remoting and apply it on remote PC's basic file to create a new file.

**Comment by GrzegorzBlok** [comment]
Sorry for late answer. I have never tested it with powershell. Since FastRsyncNet is .net assembly I think that it is possible to use it with powershell. You may also want to check https://github.com/OctopusDeploy/Octodiff command line tool that FastRsyncNet is based on.
