### ISSUE TITLE
Any tips on how to deal with Unity resource files compressed with LZ4?

### ISSUE THREAD

**Issue by aizuon** [GrzegorzBlok/FastRsyncNet#13]
Hello, first of all, thanks for this great tool. 

I would like to use it on a game project I'm working on. Specifically, to provide a method to patch changed Unity resource files which are compressed with LZ4. I tested with 2 resource files with 32 KB difference. The output delta file produced by the tool was 51 MB. I tried with lower signature chunk size(minimum) and the output size reduced to 27 MB. It is a great improvement but are there any other settings I could tweak to lower the size of the delta file?

**Comment by GrzegorzBlok** [comment]
Hi,

To efficiently use rsync algorithm with compressed data it needs to be compressed with an rsync-compatible compression algorithm.

>  If you synchronize compressed file, a small change in a compressed file may force rsync algorithm to synchronize whole compressed file, instead of just the changed blocks. To fix this, a custom GZip compression method may be used that periodically reset the compressor state to make it block-sync friendly. Install FastRsyncNet.Compression package and use following method:
> 
> `FastRsync.Compression.GZip.Compress(Stream sourceStream, Stream destStream)`
> 
> To uncompress you may use any GZip method (e.g. System.IO.Compression.GZipStream).
