### ISSUE TITLE
Add xxHash3 support

### ISSUE THREAD

**Issue by kamronbatman** [GrzegorzBlok/FastRsyncNet#14]
Looks like System.IO.Hashing will support xxHash3 - .Net Standard 2, .Net Framework 4.6.2, and .Net 6/7/8.

**Comment by GrzegorzBlok** [comment]
This looks promising - I would definitely look into this. My main concern is if System.IO.Hashing.xxHash2 and System.Data.HashFunction.xxHash implementations produces the exact same results. It needs to if we are to replace System.Data.HashFunction package with System.IO.Hashing.

**Comment by kamronbatman** [comment]
I think that depends on the seed. Otherwise it should.

**Comment by GrzegorzBlok** [comment]
The System.IO.Hashing xxHash64 result is reversed when comparing to System.Data.HashFunction.xxHash. It also lacks stream API. I am currently testing the performance to see how it compares one to another.

I have some preliminary results for .NET7. Definitely more testing is needed, especially in terms of streaming.
```
|                Method |      N |          Mean |        Error |       StdDev |
|---------------------- |------- |--------------:|-------------:|-------------:|
|          DataXxHash64 |    128 |     298.62 ns |     2.378 ns |     1.986 ns |
|    DataXxHash64Stream |    128 |     287.88 ns |     4.353 ns |     4.072 ns |
|        SystemXxHash64 |    128 |      36.77 ns |     0.340 ns |     0.499 ns |
| SystemXxHash64Reverse |    128 |      37.50 ns |     0.443 ns |     0.415 ns |
|          DataXxHash64 |  16974 |  15,580.82 ns |   148.073 ns |   138.507 ns |
|    DataXxHash64Stream |  16974 |     297.93 ns |     3.886 ns |     5.319 ns |
|        SystemXxHash64 |  16974 |   2,183.05 ns |     6.782 ns |     5.295 ns |
| SystemXxHash64Reverse |  16974 |   2,224.74 ns |    13.207 ns |    12.354 ns |
|          DataXxHash64 | 356879 | 321,203.64 ns | 2,563.790 ns | 2,272.733 ns |
|    DataXxHash64Stream | 356879 |     284.13 ns |     4.254 ns |     3.980 ns |
|        SystemXxHash64 | 356879 |  45,880.04 ns |   346.116 ns |   323.757 ns |
| SystemXxHash64Reverse | 356879 |  46,096.90 ns |   473.327 ns |   442.750 ns |
```

**Comment by kamronbatman** [comment]
Yeah probably need to stream to the Append manually by using a rented buffer or stackalloc.
