### ISSUE TITLE
NuGet version 1.1.2

### ISSUE THREAD

**Issue by rasjidw** [GrzegorzBlok/FastRsyncNet#2]
NuGet has a 1.1.2 version, but the GitHub repo only has 1.0.1 and 1.1.1.

Is this just a case of missing tags, or is there more to it?

**Comment by GrzegorzBlok** [comment]
This is a case of missing tag - sorry for that. The only difference between 1.1.1 and 1.1.2 versions is this commit:
https://github.com/GrzegorzBlok/FastRsyncNet/commit/0aa26774d6155b0000aaed5ed0d1d721f5fbc7c0
