### ISSUE TITLE
Delta size is very big

### ISSUE THREAD

**Issue by Nirmalya-Kundu** [GrzegorzBlok/FastRsyncNet#3]
Hi 

I am using FastRsyncNet . Its working perfectly.

But I have noticed one problem that is the delta file size is very big almost same as as my main file size for example Screenshot_2016-05-18-19-09-05_com.example.premat.workpack_framed.png =1218 KB and delta size is :1218 KB

Can You please help me  with the  **"big delta file size issue"**

.

The implementation code is attached below

I am using it like this;

 string sourcefile = @"D:\TestSync\Screenshot_2016-05-18-19-09-05_com.example.premat.workpack_framed.png";
            string signaturefile = @"D:\TestSync\signature";
            string Destinationfile = @"\\SERVER2008\Share\TestSync1\Screenshot_2016-05-18-19-09-05_com.example.premat.workpack_framed.png";
            string Deltafile = @"\\SERVER2008\Share\TestSync1\delta";
           IProgress< ProgressReport> ProgressReport= null ;

            var signatureBuilder = new SignatureBuilder();
            using (var basisStream = new FileStream(Destinationfile, FileMode.Open, FileAccess.Read, FileShare.Read))
            using (var signatureStream = new FileStream(signaturefile, FileMode.Create, FileAccess.Write, FileShare.Read))
            {
                signatureBuilder.Build(basisStream, new SignatureWriter(signatureStream));
            }

            //var delta = new DeltaBuilder();
            //signatureBuilder.ProgressReport = new ConsoleProgressReporter();
            //using (var newFileStream = new FileStream(newFilePath, FileMode.Open, FileAccess.Read, FileShare.Read))
            //using (var signatureStream = new FileStream(signatureFilePath, FileMode.Open, FileAccess.Read, FileShare.Read))
            //using (var deltaStream = new FileStream(deltaFilePath, FileMode.Create, FileAccess.Write, FileShare.Read))
            //{
            //    delta.BuildDelta(newFileStream, new SignatureReader(signatureStream, delta.ProgressReporter), new AggregateCopyOperationsDecorator(new BinaryDeltaWriter(deltaStream)));
            //}
            var delta = new DeltaBuilder();
            
            using (var newFileStream = new FileStream(sourcefile, FileMode.Open, FileAccess.Read, FileShare.Read))
            using (var signatureStream = new FileStream(signaturefile, FileMode.Open, FileAccess.Read, FileShare.Read))
            using (var deltaStream = new FileStream(Deltafile, FileMode.Create, FileAccess.Write, FileShare.Read))
            {
                delta.BuildDelta(newFileStream, new SignatureReader(signatureStream, delta.ProgressReport), new AggregateCopyOperationsDecorator(new BinaryDeltaWriter(deltaStream)));
            }

            var deltaapp = new DeltaApplier
            {
                SkipHashCheck = true
            };
            using (var basisStream = new FileStream(Destinationfile, FileMode.Create, FileAccess.ReadWrite, FileShare.Read))
            using (var deltaStream = new FileStream(Deltafile, FileMode.Open, FileAccess.Read, FileShare.Read))
            using (var newFileStream = new FileStream(sourcefile, FileMode.Open, FileAccess.Read, FileShare.Read))
            {
                deltaapp.Apply(newFileStream, new BinaryDeltaReader(deltaStream, ProgressReport), basisStream);
            }

**Comment by GrzegorzBlok** [comment]
Without source file and destination file (and preferably the signature file as well) it's nearly impossible to conclude whether it's an algorithm issue or the delta size is valid and purely data related. Having said that the files contents are essential for further investigation.

**Comment by grzewal** [comment]
Also please note that in corner cases the delta file size can exceed either of the files (be that the source or the destination file) sizes.

**Comment by Nirmalya-Kundu** [comment]
I have uploaded old file and new file here and delta file is  in google drive .  

 I put the messy red marks on new file  for testing the sync.

Please let me know if you want any thing more.


![screenshot_2016-05-18-19-09-05_com example premat workpack_framed-newfile](https://user-images.githubusercontent.com/31956137/30426560-18dc17de-996a-11e7-93d3-67803d474d88.png)
![screenshot_2016-05-18-19-09-05_com example premat workpack_framed-oldfile](https://user-images.githubusercontent.com/31956137/30426570-21d42f20-996a-11e7-869f-03ea312e2266.png)

https://drive.google.com/file/d/0B9WqfqIbr748V0VnNWJsanFkZFE/view?usp=sharing

**Comment by Nirmalya-Kundu** [comment]
@grzewal what do you mean  by **corner cases** . Is there any way I can understand  the logic of Delta file  size. As per my understanding The delta file should consists the difference.

Regards

Nirmalya

**Comment by grzewal** [comment]
You are right that the delta file contains the diff. But it also contains some metadata. So if the differences are major (i.e you calculate a delta between a 1 byte and 1MB file) the delta itself can be bigger that 1MB.

**Comment by grzewal** [comment]
The pictures you added are identical (was that your intention). So in this case the delta is of minimal size.

**Comment by Nirmalya-Kundu** [comment]
Hello @grzewal thanks for your prompt reply. but in my case new file and old files are of same size. I have attached them at my previous message.

**Comment by Nirmalya-Kundu** [comment]
@GrzegorzBlok I forgot the post the signature file here is it. https://drive.google.com/file/d/0B9WqfqIbr748bmlJVEpVNHRqMHM/view?usp=sharing

**Comment by grzewal** [comment]
@Nirmalya-Kundu They are not only of the same size, but they are of the same content. Was that your intention? To create a delta between two files that have the exact same content?

**Comment by Nirmalya-Kundu** [comment]
@grzewal Yes you are not right about my intention of two files are not identical. I am describing you the steps I did for Sync.

1) I have only put the red marks to my new file 

2) Created signature of my old file  (without red mark)  

3) Then the new file get compared with the signature of old file

4)delta got generated(size=1218  KB) 

4) Applied delta on old file(without red mark)  for getting the red marks on it for syncing

I hope the case is much clearer now. waiting for your opinion

**Comment by grzewal** [comment]
Ok. The case is clear. But if you take a look at your post [(https://github.com/GrzegorzBlok/FastRsyncNet/issues/3#issuecomment-329449576)](https://github.com/GrzegorzBlok/FastRsyncNet/issues/3#issuecomment-329449576) where you uploaded the files you actually added two identical files (both with red lines) so it is hard to reproduce the issue. Please upload the right files first.

**Comment by Nirmalya-Kundu** [comment]
Thanks for your quick and excellent response  friend.  I have the uploaded my old file with  the state of before get synced.

Please let me know if you need anything more

![screenshot_2016-05-18-19-09-05_com example premat workpack_framed](https://user-images.githubusercontent.com/31956137/30428040-c22ef5fe-996f-11e7-8ed1-3337b696cae6.png)

**Comment by grzewal** [comment]
Here's the reason for the big delta you observe: even though for a human eye the files are quite similar they differ dramatically on the binary level. You can easily see it by doing a binary diff (using any kind of diff tool) on the source and destination files. What you will observe is that the differences will be reported in almost everywhere throughout the files. 

In order to understand why this is the case even though the files for a human look very similar is to take a look what a png format is. To make it short - png is a format that uses lossless data compression algorithm. But as many compression algorithms do a small change to an uncompressed content can result in a huge change in the compressed result. And this is what you observe. 

So even though you make what appears to be a smal change to the file content (by adding a couple of red lines) the binary result is completely different due to the fact that it undergoes compression. 

So I would say that the delta size is about correct, because on a binary level your source and destination files vary by a lot (again I encourage you to compare the files using a diff tool on a binary level). 

HTH

**Comment by Nirmalya-Kundu** [comment]
Hi 

Thanks for your clarification I will definitely do  binary diff and will let you know. 

I have one more question Can I ask it?

Regards
Nirmalya

**Comment by Nirmalya-Kundu** [comment]
I have one more question, I have noticed one thing that is if I using a complex( a png file of 1 mb or a jpg file) file the patching is not working properly. I mean to say that its not creating the new file.

Can You please tell me why is this happening.
If you want I will share you the delta, signature and the image files

**Comment by TheAifam5** [comment]
Hey,
I want to refresh this because RSync generates a lot of smaller delta than FastRsyncNet (also Octodiff).

Here are the files
[delta-test.zip](https://github.com/GrzegorzBlok/FastRsyncNet/files/1649740/delta-test.zip)

the .jar files are just a .class files from a .jar file.. (because i was testing .jar deltas and want to test how big delta is for the .class files). What I changed in java app is only a one string.

The change is really small, like 6 bytes when i was checking in 010 Editor.

RSync shows like 55bytes only.
