### ISSUE TITLE
Applying delta incrementally directly to original blob in Azure blob storage?

### ISSUE THREAD

**Issue by DaRosenberg** [GrzegorzBlok/FastRsyncNet#6]
We are building a wrapping library around FastRsyncNet that will orchestrate an outer bi-directional sync process, snapshotting of target file during the rsync transfer, along with some timestamp-based change detection to determine whether even a signature comparison in either direction is really necessary (as even generating and transmitting a signature are relatively expensive operations for our scenario). We will make this library open-source for anyone who might find this functionality useful.

The library will abstract the underlying file storage, and provide implementations for file system and Azure Blob Storage. Our intended application of the library will primarily use Azure Blob Storage. In your readme.md you provide an example of generating a signature from, and storing it in, blob storage. That's all good and very straightforward - it's all streams anyway.

Our scenario will also require applying a delta directly to the original blob inside of blob storage. This is because our files will get quite large (several hundred MB) and reading the entire base file from blob storage and writing the entire target blob back to blob storage every time we apply a delta (which typically will only change a few hundred bytes) would be problematic from perf and scalability standpoints, since reading and writing against blob storage is always done over the network. It would also incur significant cost since blob storage is metered by number of access operations.

As far as I can tell from the FastRsyncNet API and implementation, the updated target file is always written in its entirety, to a separate stream. In your assessment, is there any way we can overcome this and end up with an implementation that, using whatever blob storage APIs are available (perhaps not streams), applies a delta more granularly by making incremental modifications to the original blob?

One obvious issue is that the `DeltaApplier` reads the base stream and writes the target stream simultaneously, so if they represent the same blob things will get real messy real fast. :) But this can easily be overcome by leveraging the blob storage snapshot capability to snapshot the target blob, let the reader read from the snapshot and the writer write to the original blob, and then delete the snapshot after the delta application has finished.

Many thanks in advance for your advice.

**Comment by grzewal** [comment]
Hi! 

On a conceptual level a delta file consists of two types of commands:

- _copy-byte-range-from-source-command_
- _insert-bytes-command_

If you suspect that most of the times the changes will be made somewhere in the middle of the file by creating its snapshot you could potentially leverage one particular optimization. 

On a conceptual level having two **identical** files:

- _to-be-patched-file_ (that will be used as the _to-write-to-file_ when applying delta)
- _snapshot-of-to-be-patched-file_ (that will be used as the _to-read-from-file_ when applying delta)

would allow you to skip the first _copy-byte-range-from-source-command_ since the _to-be-patched-file_ already contains the necessary bytes . 
On the other hand in case the result file should be smaller than the _to-be-patched-file_ (because some bytes were removed) you would need to make sure to truncate the _to-be-patched-file_ accordingly. 

In order to achieve this optimization you would need to implement a specialized version of `DeltaApplier` that would do the above leveraging Blob Storage capabilities for creating blob snapshots. 

HTH,

**Comment by DaRosenberg** [comment]
Hi,

Thanks, that clarifies a lot! It seems we had similar thoughts or leveraging the blob storage snapshot capability.

It's not entirely clear to me how we could safely skip the first *copy-byte-range-from-source-command* - how can the customized `DeltaApplier` know that those bytes don't contain any changes?

In any case, if there is no conceptual *delete-bytes-command* in an rsync delta, then I think the benefit of this optimization in our case will be limited. Our files will quite frequently shrink as well as grow, and this can happen anywhere in the file.

Sounds like perhaps it's better to simply bite the bullet and write the whole thing then.

Wouldn't it be great if rsync was implemented at the blob storage layer?

**Comment by grzewal** [comment]
Hi! 

To answer your question - you could only skip the first _copy-byte-range-from-source-command_ if it was overall the **first** command in the delta. 

Let me know if it's clearer now. If not I will try to provide a more detailed answer. 

HTH,

**Comment by DaRosenberg** [comment]
Ahh, now I get it. By "copy from source" you are of course referring to the base file as the source, while "insert bytes" refers to bytes coming from the delta. So then, deleting a range of bytes would be encoded as two *copy-from-source* commands, one for the bytes before the delete and one for the bytes after the delete.

I'll give this some more thought, perhaps there is a potential here after all.

Meanwhile I added a suggestion for rsync support to Azure Blob Storage:
https://feedback.azure.com/forums/217298-storage/suggestions/32882617-add-rsync-support-for-blob-storage

**Comment by grzewal** [comment]
@DaRosenberg Exactly! 

As for the suggestion for Azure Blob Storage - I've already upvoted it :+1:

**Comment by TheAifam5** [comment]
@DaRosenberg @grzewal I've also already upvoted it 👍

**Comment by i00** [comment]
+1

**Comment by DaRosenberg** [comment]
MS has now declined the feature suggestion. I suspect it may be because I did not phrase it very clearly, and perhaps some folks misunderstand it and think it's about rsync support in the linux/unix file copy tool sense of the word, rather than pure protocol support... whatever the reason, it's a shame they declined the feature request, as it would be extremely useful for these kinds of bandwidth-sensitive scenarios.

**Comment by i00** [comment]
I actually want it for other purposes ... not using Azure ... so I still want to see this :(

**Comment by DaRosenberg** [comment]
@i00 I think it would be very hard to achieve.

As @grzewal pointed out, a delta has two types of "commands":

1. Copy a range of bytes from the source file
2. Write a range of bytes from the delta

Because of this, writing directly to the source file would only be possible in the following cases:

* if there are no "shifts" of position within the file, i.e. the only changes consist of in-place overwrites of the same number of bytes as the data being overwritten
* for the first contiguous unchanged range of bytes (regardless of the above)

For a generic library, these two cases are too rare to warrant making this optimization IMO.

To truly enable a useful in-place overwrite in a more broad set of circumstances would require:

* the rsync delta format to be expanded with a more expressive "instruction set" that can also convey the operation of replacing with a different size block (larger or smaller) than the range being replaced
* the underlying storage to support such operations, which is not the case for file-based streams in .NET as far as I recall

**Comment by i00** [comment]
There will be no shifts.. vhdxs are optimised for this.. they write to the end.. clear data out of the middle.. without 'closing the gaps'.. if there are gaps it will write into these first.. so just extending the file and writing changed bytes will be ok..

I imagine most large files that are edited will function this way since there is no way to create space in the middle of a file.

Kris

**Comment by DaRosenberg** [comment]
@i00 I see - if you know this to be the case, I guess it should be relatively easy to implement a custom `DeltaApplier` that ignores the "copy from source" commands and only processes the "write from delta" commands. It should then be possible to use the same underlying file as both the source and target of the delta application. But of course, your application will completely rely on the assumption that there are no "position shifts" in the file contents - if that assumption is ever violated, the resulting file would be corrupt.
