### ISSUE TITLE
Possible to update the patch basis file in-place?

### ISSUE THREAD

**Issue by i00** [GrzegorzBlok/FastRsyncNet#8]
I was wondering if it would be at all possible to modify the basis file directly in place, rather than to create a new file.. the reason that I ask is that the remote file system that I am backing is aware of changes vs new file writes for its backup.

As for things failing mid-process, the software I am writing is aware if of failures from its last backup and will re-push the entire file that failed when the connection is restored.

Great work, Thanks

**Comment by GrzegorzBlok** [comment]
The short answer is: no. See [this](https://github.com/GrzegorzBlok/FastRsyncNet/issues/6) for details.

If it doesn't answer your question, comment below so we can elaborate.

**Comment by i00** [comment]
Thanks ... I did see that but wasn't 100% sure if it was the same as what I was asking since it mentioned Azure.
